# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LegendView
                                 A QGIS plugin
 凡例を表示する
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-10-28
        copyright            : (C) 2020 by soja city.
        email                : none
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LegendView class from file LegendView.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .legend_view import LegendView
    return LegendView(iface)
