# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LegendView
                                 A QGIS plugin
 凡例を表示する
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-10-28
        git sha              : $Format:%H$
        copyright            : (C) 2020 by soja city.
        email                : none
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import re

# Import Qt compatibility module
from .qt_compat import QSettings, QTranslator, QCoreApplication, Qt, QIcon, QAction, QDockWidget, WA_DeleteOnClose, RightDockWidgetArea, translate

from qgis.core import QgsSettings, QgsMessageLog, QgsProject, QgsExpressionContextUtils

# Initialize Qt resources from file resources.py
from .resources_rc import *

# Import version information
from .version import __version__, get_version_info, get_compatibility_info

# Import the code for the DockWidget
from .legend_view_dockwidget import LegendViewDockWidget
import os.path

class LegendView:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface

        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)

        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'LegendView_{}.qm'.format(locale))

        # Try to load Qt translator
        self.translator = None
        if os.path.exists(locale_path):
            self.translator = QTranslator()
            if self.translator.load(locale_path):
                QCoreApplication.installTranslator(self.translator)
            else:
                self.translator = None
        
        # Store current locale for Python fallback translations
        self.current_locale = locale if locale in ['ja', 'en'] else 'en'

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&凡例表示')  # Default to Japanese, will be translated
        self.toolbar = None  # Initialize as None, will be created in initGui()
        
        #print "** INITIALIZING LegendView"

        self.pluginIsActive = False
        self.dockwidget = None

        # Show window if project variable contains its own name
        iface.projectRead.connect(self.checkLoadedProject)

    def __del__(self):
        if self.pluginIsActive:
            self.storeState()

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # Try Qt translation first
        translated = translate('LegendView', message)
        
        # If no translation found or same as original, try Python fallback
        if translated == message and hasattr(self, 'current_locale'):
            try:
                from .i18n.translations import translate as py_translate
                translated = py_translate('LegendView', message, self.current_locale)
            except ImportError:
                pass
        
        return translated


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar and self.toolbar is not None:
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action


    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""
        
        # Create toolbar safely during GUI initialization
        try:
            if self.toolbar is None:
                self.toolbar = self.iface.addToolBar(u'LegendView')
                self.toolbar.setObjectName(u'LegendView')
        except Exception as e:
            QgsMessageLog.logMessage(f"Error creating toolbar: {str(e)}", "LegendView", level=1)
            # Fallback: don't use toolbar if creation fails
            self.toolbar = None

        icon_path = ':/plugins/legend_view/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'凡例'),  # Default to Japanese, will be translated
            callback=self.run,
            parent=self.iface.mainWindow())

    #--------------------------------------------------------------------------

    def onClosePlugin(self):
        """Cleanup necessary items here when plugin dockwidget is closed"""

        #print "** CLOSING LegendView"

        self.storeState()

        # disconnects
        self.dockwidget.closingPlugin.disconnect(self.onClosePlugin)

        # remove this statement if dockwidget is to remain
        # for reuse if plugin is reopened
        # Commented next statement since it causes QGIS crashe
        # when closing the docked window:
        self.dockwidget = None
        
        self.pluginIsActive = False


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""

        #print "** UNLOAD LegendView"

        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&凡例表示'),  # Default to Japanese, will be translated
                action)
            self.iface.removeToolBarIcon(action)
        # remove the toolbar safely
        if self.toolbar is not None:
            try:
                del self.toolbar
            except:
                pass
            self.toolbar = None

    #--------------------------------------------------------------------------

    def run(self):
        """Run method that loads and starts the plugin"""

        if not self.pluginIsActive:
            self.pluginIsActive = True

            #print "** STARTING LegendView"

            # dockwidget may not exist if:
            #    first run of plugin
            #    removed on close (see self.onClosePlugin method)
            if self.dockwidget == None:
                # Create the dockwidget (after translation) and keep reference
                self.dockwidget = LegendViewDockWidget(self.iface)
                self.dockwidget.setAttribute(WA_DeleteOnClose)

            # connect to provide cleanup on closing of dockwidget
            self.dockwidget.closingPlugin.connect(self.onClosePlugin)

            self.restoreState()

        if self.dockwidget:
            if self.dockwidget.isFloating():
                self.dockwidget.activateWindow()
            else:
                self.dockwidget.raise_()
                
    def onProjectClose(self):
        if self.dockwidget:
            self.dockwidget.close()

    def storeState(self):
        if not self.dockwidget:
            return

        s = QgsSettings()
        is_floating = "1" if self.dockwidget.isFloating() else "0"
        s.setValue("LegendView/isfloating", is_floating)
        s.setValue("LegendView/geometry", self.dockwidget.saveGeometry())

    def restoreState(self):
        s = QgsSettings()
        is_floating = s.value("LegendView/isfloating", "0") == "1"

        if is_floating:
            self.iface.addDockWidget(RightDockWidgetArea, self.dockwidget)
            geometry = s.value("LegendView/geometry", "")
            if not geometry.isEmpty():
                self.dockwidget.restoreGeometry(bytearray(geometry))
            self.dockwidget.setFloating(True)

        else:
            self.dockwidget.setFloating(False)
            if not self.iface.mainWindow().restoreDockWidget(self.dockwidget):
                self.iface.addDockWidget(RightDockWidgetArea, self.dockwidget)

        self.dockwidget.show()

    def checkLoadedProject(self):
        # Do nothing if already active
        if self.pluginIsActive:
            return

        # Tests whether a variable with "plugin_" + menu name exists in the scope.
        ecs = QgsExpressionContextUtils.projectScope(QgsProject.instance())
        menu_text = re.sub(r"^&", "", self.menu)
        name = f"plugin_{menu_text}"
        if ecs.hasVariable(name):
            value = ecs.variable(name)
            if value == "1":
                self.run()

